using System.ComponentModel.DataAnnotations;

namespace TicketMaster.Models
{
    /// <summary>
    /// Represents an electronic ticket generated after a successful reservation payment.
    /// Contains all information necessary for QR code generation, PDF display, and entry validation.
    /// </summary>
    public class Ticket
    {
        /// <summary>
        /// Unique identifier of the ticket.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Unique ticket number.
        /// Format: TKT-{timestamp}-{seatId}.
        /// Used for identification and PDF generation.
        /// Maximum length: 100 characters.
        /// </summary>
        [Required, MaxLength(100)]
        public string TicketNumber { get; set; } = string.Empty;

        /// <summary>
        /// QR code data in JSON format.
        /// Contains information such as eventId, seatId, ticketNumber, etc.
        /// Used to generate the QR code image.
        /// </summary>
        [Required]
        public string QrCodeData { get; set; } = string.Empty;

        /// <summary>
        /// URL of the generated QR code image.
        /// Generated by QR code service (e.g., api.qrserver.com).
        /// Used for display on PDFs and mobile tickets.
        /// Maximum length: 500 characters.
        /// </summary>
        [MaxLength(500)]
        public string QrCodeUrl { get; set; } = string.Empty;

        /// <summary>
        /// Timestamp when the ticket was generated.
        /// Set automatically when the ticket is created.
        /// </summary>
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Indicates whether the ticket has been used.
        /// Set to true when the QR code is scanned at the venue entrance.
        /// </summary>
        public bool IsUsed { get; set; } = false;

        /// <summary>
        /// Timestamp when the ticket was used.
        /// Null if the ticket has not been used.
        /// Recorded when the QR code is validated at entry.
        /// </summary>
        public DateTime? UsedAt { get; set; }

        /// <summary>
        /// ID of the reservation associated with this ticket.
        /// </summary>
        public int ReservationId { get; set; }

        /// <summary>
        /// Reference to the reservation.
        /// </summary>
        public Reservation Reservation { get; set; } = null!;

        /// <summary>
        /// ID of the seat for which this ticket was issued.
        /// </summary>
        public int SeatId { get; set; }

        /// <summary>
        /// Reference to the seat.
        /// </summary>
        public Seat Seat { get; set; } = null!;
    }
}
